// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EventsServiceConsumer is an autogenerated mock type for the EventsServiceConsumer type
type EventsServiceConsumer struct {
	mock.Mock
}

// ConsumeEvents provides a mock function with given fields:
func (_m *EventsServiceConsumer) ConsumeEvents() {
	_m.Called()
}

// NewEventsServiceConsumer creates a new instance of EventsServiceConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventsServiceConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventsServiceConsumer {
	mock := &EventsServiceConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
