services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "url_shortener_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user"
    ports:
      - "5440:5432"
    volumes:
      - pg_vol:/var/lib/postgresql/data
    networks:
      - service_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "url_shortener_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_vol:

networks:
  service_network:
    driver: bridge