// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	domain "CoolUrlShortener/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// EventsWriter is an autogenerated mock type for the EventsWriter type
type EventsWriter struct {
	mock.Mock
}

// Insert provides a mock function with given fields: events
func (_m *EventsWriter) Insert(events []domain.URLEvent) error {
	ret := _m.Called(events)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]domain.URLEvent) error); ok {
		r0 = rf(events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewEventsWriter creates a new instance of EventsWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventsWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventsWriter {
	mock := &EventsWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
